"""Added summary field to Base model

Revision ID: 61798c5e81b3
Revises: 2e72a5329082
Create Date: 2025-03-17 09:42:18.860258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61798c5e81b3'
down_revision: Union[str, None] = '2e72a5329082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('summary', sa.String(), nullable=False))
    op.add_column('notes_versions', sa.Column('summary', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes_versions', 'summary')
    op.drop_column('notes', 'summary')
    # ### end Alembic commands ###
