"""Added notes_versions table.

Revision ID: a3a1fcef062b
Revises: 1304390fdc58
Create Date: 2025-03-15 15:31:15.476539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3a1fcef062b'
down_revision: Union[str, None] = '1304390fdc58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'version_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
